<a href="https://colab.research.google.com/github/lesya7maltseva/Pandas-Statistics-/blob/main/Pandas_%D0%BE%D1%87%D0%B8%D1%81%D1%82%D0%BA%D0%B0_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание № 1

In [ ]:
import pandas as pd
import numpy as np

#считываем файл в датафрэйм, из описания файла выбираем нужные столбцы и с помощью iloc сохраняем в новый фрэйм, с которым и работаем
df_raw = pd.read_csv('raw_horses.csv', na_values= '?',usecols= [0,1,3,4,5,6,10,22],
                     names = ["surgery", "Age", "rectal_temperature", "pulse", "respiratory_rate", "temperature_of_extremities", "pain", "outcome"])
df_raw.describe()

,surgery,Age,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,pain,outcome
count,299.000000,300.000000,240.000000,276.000000,242.000000,244.000000,245.00000,299.000000
mean,1.397993,1.640000,38.167917,71.913043,30.417355,2.348361,2.95102,1.551839
std,0.490305,2.173972,0.732289,28.630557,17.642231,1.045054,1.30794,0.737187
min,1.000000,1.000000,35.400000,30.000000,8.000000,1.000000,1.00000,1.000000
25%,1.000000,1.000000,37.800000,48.000000,18.500000,1.000000,2.00000,1.000000
50%,1.000000,1.000000,38.200000,64.000000,24.500000,3.000000,3.00000,1.000000
75%,2.000000,1.000000,38.500000,88.000000,36.000000,3.000000,4.00000,2.000000
max,2.000000,9.000000,40.800000,184.000000,96.000000,4.000000,5.00000,3.000000

Задание № 2

In [ ]:
df_work_nanfree = df_raw.dropna()
df_work_nanfree.describe(include = 'all')

,surgery,Age,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,pain,outcome
count,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000
mean,1.435065,1.623377,38.163636,70.844156,29.649351,2.220779,2.694805,1.480519
std,0.497383,2.151388,0.731890,29.609690,16.122299,1.061795,1.217132,0.697529
min,1.000000,1.000000,35.400000,36.000000,9.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,37.800000,48.000000,18.000000,1.000000,2.000000,1.000000
50%,1.000000,1.000000,38.200000,60.000000,27.000000,2.500000,3.000000,1.000000
75%,2.000000,1.000000,38.500000,88.000000,36.000000,3.000000,3.000000,2.000000
max,2.000000,9.000000,40.800000,184.000000,88.000000,4.000000,5.000000,3.000000

In [ ]:
#квартили и межквартильный размах.определение выбросов
q1_rt = df_raw['rectal_temperature'].quantile(0.25)
q3_rt = df_raw['rectal_temperature'].quantile(0.75)
iqr_rt = q3_rt - q1_rt
lower_rt = q1_rt - (1.5 * iqr_rt)
higher_rt = q3_rt + (1.5 * iqr_rt)
print(iqr_rt)
print(lower_rt)
print(higher_rt)

In [ ]:
df_out_rt = df_raw[~df_raw['rectal_temperature'].between(lower_rt,higher_rt,inclusive = True)]
df_out_rt.dropna()

In [ ]:
q1_pulse = df_raw['pulse'].quantile(0.25)
q3_pulse = df_raw['pulse'].quantile(0.75)
iqr_pulse = q3_pulse - q1_pulse
lower_pulse = q1_pulse - (1.5 * iqr_pulse)
higher_pulse = q3_pulse + (1.5 * iqr_pulse)
print(iqr_pulse)
print(lower_pulse)
print(higher_pulse)

40.0
-12.0
148.0

In [ ]:
# Все выбросы:
df_out_pulse = df_raw[~df_raw['pulse'].between(lower_pulse,higher_pulse,inclusive = True)]
df_out_pulse.dropna()

In [ ]:
q1_rr = df_raw['respiratory_rate'].quantile(0.25)
q3_rr = df_raw['respiratory_rate'].quantile(0.75)
iqr_rr = q3_rr - q1_rr
lower_rr = q1_rr - (1.5 * iqr_rr)
higher_rr = q3_rr + (1.5 * iqr_rr)
print(iqr_rr)
print(lower_rr)
print(higher_rr)

17.5
-7.75
62.25

surgery                        1.0
Age                            1.0
rectal_temperature            38.2
pulse                         64.0
respiratory_rate              24.5
temperature_of_extremities     3.0
pain                           3.0
outcome                        1.0
dtype: float64

In [ ]:
# Все выбросы:
df_out_rr = df_raw[~df_raw['respiratory_rate'].between(lower_rr,higher_rr,inclusive = True)]
df_out_rr.dropna()

<ipython-input-30-1895a88a7c4f>:2: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  df_out_rr = df_raw[~df_raw['respiratory_rate'].between(lower_rr,higher_rr,inclusive = True)]

,surgery,Age,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,pain,outcome
3,1.0,9,39.1,164.0,84.0,4.0,2.0,2.0
82,1.0,9,38.1,100.0,80.0,3.0,3.0,1.0
84,1.0,1,37.8,60.0,80.0,1.0,2.0,1.0
103,1.0,9,38.0,140.0,68.0,1.0,3.0,1.0
120,1.0,1,39.4,54.0,66.0,1.0,2.0,1.0
125,1.0,1,38.0,42.0,68.0,4.0,3.0,1.0
244,1.0,9,38.2,124.0,88.0,1.0,2.0,1.0
255,1.0,9,38.8,184.0,84.0,1.0,4.0,2.0

По моему мнению, выбросы не являются выбросами. Учитывая, специфику данных и то что животные попали в больницу. Например, если посмотреть на данные по пульсу и температуре, те животные у кого были высокие показатели - не выжили.(Пульс больше 78, температура больше 40 или меньше 36) Что касается частоты дыхания, этот показатель тоже может учащаться при боезни или травме. К тому же нет прямой связи между повышением частоты дыхания и смертью животного. Максимальное значение - 88, но животное выжило. А при 84 умерло - но в этом случае были повышены пульс и температура.

Задание № 3

In [ ]:
(df_raw.isna().mean() * 100).round(2)

surgery                        1.0
Age                            1.0
rectal_temperature            38.2
pulse                         64.0
respiratory_rate              24.5
temperature_of_extremities     3.0
pain                           3.0
outcome                        1.0
dtype: float64

In [ ]:
df_work = df_raw.copy()
# Поскольку в описании данных Возраста есть только 1 или 2, а в наших данных 9, логично предположить ошибку и заменить 9 на 2
df_work.loc[df_work['Age'] == 9,'Age'] = 2

In [ ]:
# Делаем предположение, что показатели пульса и частоты дыхания могут зависеть от возрастных групп:
df_1 = df_raw.loc[df_raw['Age'] == 1]
df_1.pulse.median()

60.0

In [ ]:
df_work.loc[(df_work['Age'] == 1) & (df_work['pulse'].isna()),'pulse'] = df_1['pulse'].median()

In [ ]:
df_2 = df_raw.loc[df_raw['Age'] == 2]
df_2['pulse'].median()
# Разница существенна, заполняем на основании возрастов

124.0

In [ ]:
df_work.loc[(df_work['Age'] == 2) & (df_work['pulse'].isna()),'pulse'] = df_2['pulse'].median()

In [ ]:
# для частоты дыхания как меняется медиана, в заисимости от возрастных групп и если брать общую:
print(df_1['respiratory_rate'].median())
print(df_2['respiratory_rate'].median())
print(df_raw['respiratory_rate'].median())
# изменения довольно существенные, стоит заменить пропуски медианой в зависимости от возраста

24.0
49.0
24.5

In [ ]:
df_work['respiratory_rate'] = df_work['respiratory_rate'].fillna(df_work.groupby('Age')['respiratory_rate'].transform('median'))
df_work

In [ ]:
# для частоты температуры как меняется медиана, в заисимости от возрастных групп и если брать общую:
print(df_1['rectal_temperature'].median())
print(df_2['rectal_temperature'].median())
print(df_raw['rectal_temperature'].median())
# изменения незначительные
# а если в зависимости от проведенной операции:
df_surgery = df_raw.loc[df_raw['surgery'] == 1]
df_therapy = df_raw.loc[df_raw['surgery'] == 2]
print(df_surgery['rectal_temperature'].median())
print(df_therapy['rectal_temperature'].median())
print(df_raw['rectal_temperature'].median())
# разница не существенна, предлагаю заполнить медианой по столбцу температуры без категорий

In [ ]:
df_work.loc[df_work['rectal_temperature'].isna(),'rectal_temperature'] = df_work['rectal_temperature'].median()
df_work

In [ ]:
# Предлагаю заполнение уровня боли сделать на основании категории проведения операции, поскольку такая взаимосвязь более логична, нежели возраста.
df_work['pain'] = df_work['pain'].fillna(df_work.groupby('surgery')['pain'].transform(lambda x: x.mode()[0]))
df_work

,surgery,Age,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,pain,outcome
count,299.000000,300.000000,300.000000,300.000000,242.000000,300.000000,300.000000,299.000000
mean,1.397993,1.080000,38.174333,71.386667,30.417355,2.470000,2.840000,1.551839
std,0.490305,0.271746,0.654831,27.968278,17.642231,0.975845,1.270083,0.737187
min,1.000000,1.000000,35.400000,30.000000,8.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,37.900000,48.000000,18.500000,1.000000,2.000000,1.000000
50%,1.000000,1.000000,38.200000,60.000000,24.500000,3.000000,3.000000,1.000000
75%,2.000000,1.000000,38.500000,88.000000,36.000000,3.000000,4.000000,2.000000
max,2.000000,2.000000,40.800000,184.000000,96.000000,4.000000,5.000000,3.000000

In [ ]:
# Оставшийся показатель является субъективной оценкой периферического кровообращения, из чего можно предполагать отсутствие его связи с остальными метриками,
# но проверим моду в зависимости от возраста и операций:
print(df_1['temperature_of_extremities'].mode())
print(df_2['temperature_of_extremities'].mode())
print(df_raw['temperature_of_extremities'].mode())

print(df_surgery['temperature_of_extremities'].mode())
print(df_therapy['temperature_of_extremities'].mode())
print(df_raw['temperature_of_extremities'].mode())
# Зависимость не подтвердилась:

In [ ]:
df_work['temperature_of_extremities'] = df_work['temperature_of_extremities'].fillna(3.0)
# Что касается последней строчки где неизвестно была ли операция или нет. Моя идея заключалась в том чтоб сравнить исход лечения и уровень боли.
# В итоге имеем с болью 4: 10 перенесших лечение  и 27 умерших, я бы предположила, что и в этом случае животное умерло.
# Относительно операций на животных с уровнем боли 4: 28 проведена операция и 10 без оперативного вмешательства.
# Имея эти данные я бы предположила, что была проведена операция, животное не выжило
# С другой стороны 1 строчка с довольно средними данными против 299 заполненных.
# Что стоит выбрать в этом случае? Заполнять на основе предположений или игнорировать эту строчку в рассчетах?
df_work.groupby('pain')['outcome'].value_counts()
df_work.groupby('pain')['surgery'].value_counts()

In [ ]:
# На мой взгляд, данные не сильно исказили  относительно начальных.
# А в целом на сколько должна быть разница, чтобы мы могли сказать, что искажение сильное? На +-5% или больше/меньше?
df_work.describe()

,surgery,Age,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,pain,outcome
count,299.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,299.000000
mean,1.397993,1.080000,38.174333,71.386667,29.510000,2.470000,2.840000,1.551839
std,0.490305,0.271746,0.654831,27.968278,16.189613,0.975845,1.270083,0.737187
min,1.000000,1.000000,35.400000,30.000000,8.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,37.900000,48.000000,20.000000,1.000000,2.000000,1.000000
50%,1.000000,1.000000,38.200000,60.000000,24.000000,3.000000,3.000000,1.000000
75%,2.000000,1.000000,38.500000,88.000000,36.000000,3.000000,4.000000,2.000000
max,2.000000,2.000000,40.800000,184.000000,96.000000,4.000000,5.000000,3.000000

In [ ]:
df_raw.describe()

,surgery,Age,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,pain,outcome
count,299.000000,300.000000,240.000000,276.000000,242.000000,244.000000,245.00000,299.000000
mean,1.397993,1.080000,38.167917,71.913043,30.417355,2.348361,2.95102,1.551839
std,0.490305,0.271746,0.732289,28.630557,17.642231,1.045054,1.30794,0.737187
min,1.000000,1.000000,35.400000,30.000000,8.000000,1.000000,1.00000,1.000000
25%,1.000000,1.000000,37.800000,48.000000,18.500000,1.000000,2.00000,1.000000
50%,1.000000,1.000000,38.200000,64.000000,24.500000,3.000000,3.00000,1.000000
75%,2.000000,1.000000,38.500000,88.000000,36.000000,3.000000,4.00000,2.000000
max,2.000000,2.000000,40.800000,184.000000,96.000000,4.000000,5.00000,3.000000